platform :ios, '8.0'
use_frameworks!

target 'SFA' do
    
pod 'R.swift'
pod 'JRSwizzle'
pod 'SwifterSwift'
pod 'SwiftyTimer'
pod 'Localize-Swift'
pod 'SnapKit', '~> 4.0.0'#,'~>3.0.0'
pod 'Moya','10.0.1'
pod 'Moya/RxSwift'
pod 'RxCocoa','4.1.1'
pod 'RxSwift','4.0'
pod 'SwiftyJSON'
pod 'ObjectMapper', '~>3.1'
pod 'Kingfisher'#, '~>3.13.0'
pod 'Moya-ModelMapper'
pod 'Moya-ModelMapper/RxSwift'
pod 'CryptoSwift', '~> 0.7.1'

end

