platform :ios, '8.0'
use_frameworks!

target 'SFA' do

pod 'R.swift'
pod 'JRSwizzle'
pod 'SwifterSwift'
pod 'CocoaMQTT'
pod 'SwiftyTimer'
pod 'PlainPing'
pod 'Localize-Swift'
pod 'SnapKit', '~> 4.0.0'#,'~>3.0.0'
pod 'Moya'
pod 'Moya/RxSwift'
pod 'RxCocoa'
pod 'RxSwift'
pod 'SwiftyBeaver'
pod 'SwiftyJSON'
pod "RxGesture"
pod 'CryptoSwift' ,'~> 0.7.0' #, '~>0.6.9'
pod 'ObjectMapper', '~>3.1'
pod 'Kingfisher'#, '~>3.13.0'
pod 'MJRefresh'
pod 'Moya-ModelMapper'
pod 'Moya-ModelMapper/RxSwift'
pod 'HCSStarRatingView', '~> 1.5'
pod 'RealReachability'
pod 'Watchdog'
pod 'SSZipArchive'
end

